### ISSUE TITLE
Typo CommandCreating

### ISSUE THREAD

**Issue by h0wXD** [amuratgencay/PostgreSQL.ApplicationInsights#1]
https://github.com/amuratgencay/PostgreSQL.ApplicationInsights/blob/bb7e8a84e1ff2ba7fbc6344e9d6275720130c351/PostgreSQL.ApplicationInsights.Interceptor/PostgreSqlInterceptor.cs#L31

Should this be nameof(CommandCreating)?

**Comment by amuratgencay** [comment]
copy/paste mistake

**Comment by amuratgencay** [comment]
I fixed that.
